name: run-tests
on: [push]
jobs:
    run-part1-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Java 8
              uses: actions/setup-java@v4
              with:
                distribution: 'oracle'
                java-version: '8'
            - name: Run the project
              run: |
                javac Main.java
                java Main
